services:

  front:
    build: user-interface
    restart: unless-stopped
    volumes:
      - ./user-interface:/app
    ports:
      - 5173:5173
    env_file:
      - .env
    # depends_on:
    #   - back
    
  back:
    # apparantly this needs to match the folder name
    build: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    env_file:
      - .env
